// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/8/2024, 9:16:10 AM
const configMerger = require("/home/maga/dev/sirius5/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/maga/dev/sirius5/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/plugins/**/*.{js,ts,mjs}","/home/maga/dev/sirius5/composables/**/*.{js,ts,mjs}","/home/maga/dev/sirius5/utils/**/*.{js,ts,mjs}","/home/maga/dev/sirius5/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius5/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/home/maga/dev/sirius5/.site-build/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
