// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/9/2024, 12:01:50 AM
const configMerger = require("/home/maga/dev/sirius-studio-cms/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/maga/dev/sirius-studio-cms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/plugins/**/*.{js,ts,mjs}","/home/maga/dev/sirius-studio-cms/composables/**/*.{js,ts,mjs}","/home/maga/dev/sirius-studio-cms/utils/**/*.{js,ts,mjs}","/home/maga/dev/sirius-studio-cms/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/maga/dev/sirius-studio-cms/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/home/maga/dev/sirius-studio-cms/.site-build/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
